# -*- coding: utf-8 -*-
"""Application_Regex_Index_Search_(kreyolID).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDtCbNl2rEb3CwkofW6VGISgZ8kSAe8-

# Welcome in the first version of the Kreyol Regex Index Search!

Based on regex and pos-annotation, the project has for purpose to distinguish syntactically between four Antillean French-based Creoles, which are:
- Guadeloupean - aka _gdl_ *
- Guyanese - aka _gfr_ *
- Haitian - aka _hcr_ *
- and Martinican - aka _mcq_ *

*_wals language code_

The usage of this notebook is pretty simple: you are entering a syntactic formula of your choice, and the percentage of matching sentences per creoles will be displayed, as well as the sentences themselves.

Let's look a bit more into the query itself. It has the shape [_form/upos_], meaning "I'm looking for this word(form) being this particular grammatical class (upos)".
 ```
 Query Exemple: ap/AUX
 # Here I'm looking for the wordform "ap" used as an auxilliary (which exists only in Haitian)
 ```
If you want to search for a whole group or a sentence, make sure to put a space between the words and stack them up, like this [_form/upos_ _form/upos_ _form/upos_ _etc._]. The point '.' is also useful here. Used like this [_./AUX_], the query will search over all wordforms that are auxiliaries. Following the same logic, [_ap/._] will search for the wordform 'ap' being any _upos_.

Possible _upos_ list (from [Universal Dependencies](https://universaldependencies.org/u/pos/)):
- ADJ - adjectif
- ADP - adposition (preposition like postposition)
- ADV - adverb
- AUX - auxiliary (something that helps another verb to be conjugated)
- CCONJ - coordination conjonction
- DET - determiner
- INTJ - interjection
- NOUN - clear as itself
- NUM - numerical
- PART - particule
- PRON - pronoun
- PROPN - proper noun
- PUNCT - punctuation
- SCONJ - subordination conjonction
- VERB - clear as itself

### Steps to make it run:
1. Open the menu on the left to upload the _Regex_Index_Search.ipynb_ file and the zipped _linearized\_corpora_ folder (follows the Folder icon 📁, then the Upload icon ⬆).
2. Run the first cell to import the libraries.
3. Entry the query of your choice in the second cell and run.
4. Enjoy the results.
"""

# Needed librairies + unzipping
!unzip /content/linearized_corpora.zip
!pip install pyconll
import glob, os, json, re, sys
sys.path.append('/content')
from Regex_Index_Search import load_index, query_to_regex, search, compute_stats

def search_and_display(query):
  """Search over the four corpora and displays the results."""
  index = load_index("/content/linearized_corpora")
  results = search(query, index)
  stats = compute_stats(results, index)

  print(f"Percentage of sentences matching the query {query}:\n")
  for variety, info in stats['by_variety'].items():
    percentage = info['percentage']
    print(f"{variety} corpus -> {percentage}% of matching sentences.")

  #answer = input('\nPrint the matching sentences? [y/n]\n')
  #if answer == 'y':
  print(f'\nResulting sentences matching the query {query}:\n')
  for match in results:
      print(f"{match['sent_id']} - {match['text']}")
  #else:
  #  print("Search done.")

#@markdown ### Enter your query just here:
query = "ap/AUX" # @param {"type":"string"}
search_and_display(query)